### ISSUE TITLE
TVMDBG Roadmap

### ISSUE THREAD

**Issue by siju-samuel** [siju-samuel/tvmdbg#20]
Plan of TVMDBG
- [x ] Show fused graph summary
- [x ] Perform debug run and show node details(inputs/outputs)
- [x ] Run without debug
- [ ] Call graph run-time n times from UI
- [ ]Support check for NAN in data and break
- [ ]Support check for INF in data and break
- [ ]Support for step debug(debug node by node)
- [ ]Support changing node input values and running a specific node
- [ ]Support inject node input values from a dump file
- [ ]Support dumping of node outputs to a file
- [ ]Support comparison of node output with a dump output
- [ ]Support profiler for performance debugging

**Comment by joyalbin** [comment]
add two flags debug and dbgobj.
